#!/bin/sh
set -eu
case "$1" in
    remove|purge)
        if command -v glib-compile-schemas >/dev/null 2>&1; then
            glib-compile-schemas /usr/share/glib-2.0/schemas
        fi
        ;;
esac
